version: '3'
services:

  api:
    container_name: desafioneoway
    build: .
    ports:
      - "8095:8095"
    depends_on:
      - db
    networks:
      - desafioneoway_fullstack
    image: desafioneoway

  db:
    image: postgres
    expose:
      - 5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: floripa@123
      POSTGRES_DB: postgres

  pgadmin:
    container_name: pdgdmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgress
      PGADMIN_DEFAULT_PASSWORD: floripa@123
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./db/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5434:5434"
    networks:
      - desafioneoway_fullstack
    logging:
      driver: none
    restart: unless-stopped

volumes:
  db_postgres:
  pgadmin:

# Networks to be created to facilitate communication between containers
networks:
  desafioneoway_fullstack:
    driver: bridge
