
version: '3'
services:
  app:
    container_name: desafioneoway
    build: .
    ports: 
      - 8191:8191 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres          
    networks:
      - desafioneoway_fullstack


  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER= postgres  
      - POSTGRES_PASSWORD=floripa@123
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    ports:
      - '5434:5434'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - desafioneoway_fullstack
    
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres
  #     PGADMIN_DEFAULT_PASSWORD: floripa@123
  #   depends_on:
  #     - fullstack-postgres
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - desafioneoway_fullstack
  #   restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  desafioneoway_fullstack:
    driver: bridge
